# Generated by Django 4.0.5 on 2022-06-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(default='static/images/isaac.png', null=True, upload_to='image/'),
        ),
    ]
