# Generated by Django 4.0.5 on 2022-06-08 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0002_newsletterrecipients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsLetterRecipients',
        ),
    ]
